# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqKgcX6JFSLp9V3dzxhYnT0iSVz4bRnG
"""

import os
import re
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.amp import GradScaler, autocast
from torch.optim.swa_utils import AveragedModel, SWALR
import cv2
import albumentations as A
from albumentations.pytorch import ToTensorV2
import timm
from timm.utils import ModelEmaV2
from timm.scheduler.cosine_lr import CosineLRScheduler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from glob import glob
import kagglehub
from tqdm import tqdm
import gc

from config import cfg


# 1. Инициализация директорий
os.makedirs(cfg.CHECKPOINT_DIR, exist_ok=True)
os.makedirs(cfg.BEST_MODELS_DIR, exist_ok=True)

# 2. Утилиты и метрики
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(cfg.SEED)
print(f"Device: {cfg.DEVICE} | Image Size: {cfg.IMG_SIZE}x{cfg.IMG_SIZE}")

def parse_checkpoint_name(path):
    filename = os.path.basename(path)
    match = re.search(r"fold(\d+)_epoch(\d+)_f1([\d.]+)\.pth", filename)
    if match:
        return {
            "fold": int(match.group(1)),
            "epoch": int(match.group(2)),
            "f1": float(match.group(3))
        }
    return None

def save_best(model, f1, epoch, fold):
    old_best = glob(os.path.join(cfg.BEST_MODELS_DIR, f"best_fold{fold}_*.pth"))
    for f in old_best:
        os.remove(f)

    path = os.path.join(cfg.BEST_MODELS_DIR, f"best_fold{fold}_epoch{epoch}_f1{f1:.5f}.pth")
    torch.save(model.state_dict(), path)
    print(f"New best for Fold {fold}: F1 = {f1:.5f} (Saved to {path})")

class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0, label_smoothing=0.1):
        super().__init__()
        self.gamma = gamma
        self.smooth = label_smoothing

    def forward(self, logits, targets):
        ce = F.cross_entropy(logits, targets, reduction='none', label_smoothing=self.smooth)
        pt = torch.exp(-ce)
        return ((1 - pt) ** self.gamma * ce).mean()

# 3. Датасет и аугментации
class_to_idx = {
    "Апельсин": 0, "Бананы": 1, "Груши": 2, "Кабачки": 3, "Капуста": 4,
    "Картофель": 5, "Киви": 6, "Лимон": 7, "Лук": 8, "Мандарины": 9,
    "Морковь": 10, "Огурцы": 11, "Томаты": 12,
    "Яблоки зелёные": 13, "Яблоки красные": 14
}

class MyDataset(Dataset):
    def __init__(self, paths, labels, transform=None):
        self.paths = paths
        self.labels = labels
        self.transform = transform

    def __len__(self): return len(self.paths)
    def __getitem__(self, i):
        p = self.paths[i]
        img = cv2.imdecode(np.fromfile(p, dtype=np.uint8), cv2.IMREAD_COLOR)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if self.transform:
            img = self.transform(image=img)['image']
        return img, self.labels[i]

train_transforms = A.Compose([
    A.Resize(height=cfg.IMG_SIZE + 32, width=cfg.IMG_SIZE + 32),
    A.RandomResizedCrop(size=(cfg.IMG_SIZE, cfg.IMG_SIZE), scale=(0.8, 1.0), ratio=(0.9, 1.11)),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomRotate90(p=0.3),
    A.Affine(translate_percent=0.05, scale=(0.95, 1.05), rotate=(-15, 15), p=0.4),
    A.OneOf([
        A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.0, p=1.0),
        A.GaussianBlur(blur_limit=(3, 5), p=1.0),
        A.CLAHE(p=1.0),
    ], p=0.4),
    A.CoarseDropout(num_holes_range=(1, 4), hole_height_range=(1, 32), hole_width_range=(1, 32), p=0.2),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

val_transforms = A.Compose([
    A.Resize(height=cfg.IMG_SIZE + 32, width=cfg.IMG_SIZE + 32),
    A.CenterCrop(height=cfg.IMG_SIZE, width=cfg.IMG_SIZE),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

# TTA (12 комбинаций: 3 скейла * 2 флипа * 2 поворота)
tta_transforms = []
for scale in [0.95, 1.00, 1.05]:
    for hflip in [False, True]:
        for rot in [0, 90]:
            tf = A.Compose([
                A.Resize(height=int(cfg.IMG_SIZE * scale) + 32, width=int(cfg.IMG_SIZE * scale) + 32),
                A.CenterCrop(height=cfg.IMG_SIZE, width=cfg.IMG_SIZE),
                A.HorizontalFlip(p=1.0 if hflip else 0.0),
                A.Rotate(limit=(rot, rot), p=1.0),
                A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
                ToTensorV2(),
            ])
            tta_transforms.append(tf)

# 4. MixUp & CutMix
def mixup_data(x, y, alpha=0.4):
    lam = np.random.beta(alpha, alpha) if alpha > 0 else 1.0
    index = torch.randperm(x.size(0)).to(x.device)
    mixed_x = lam * x + (1 - lam) * x[index]
    return mixed_x, y, y[index], lam

def cutmix_data(x, y, alpha=0.4):
    lam = np.random.beta(alpha, alpha) if alpha > 0 else 1.0
    index = torch.randperm(x.size(0)).to(x.device)
    bbx1, bby1, bbx2, bby2 = rand_bbox(x.size(), lam)
    x[:, :, bbx1:bbx2, bby1:bby2] = x[index, :, bbx1:bbx2, bby1:bby2]
    lam = 1 - ((bbx2 - bbx1) * (bby2 - bby1) / (x.size(-1) * x.size(-2)))
    return x, y, y[index], lam

def rand_bbox(size, lam):
    W, H = size[2], size[3]
    cut_rat = np.sqrt(1. - lam)
    cut_w, cut_h = int(W * cut_rat), int(H * cut_rat)
    cx, cy = np.random.randint(W), np.random.randint(H)
    return (max(0, cx - cut_w//2), max(0, cy - cut_h//2),
            min(W, cx + cut_w//2), min(H, cy + cut_h//2))

# 5. Инициализация данных и модели
data_path = kagglehub.competition_download('dl-lab-1-image-classification')
train_root = os.path.join(data_path, "train", "train")

all_paths, all_labels = [], []
for cls in os.listdir(train_root):
    cls_path = os.path.join(train_root, cls)
    if not os.path.isdir(cls_path): continue
    for plu in os.listdir(cls_path):
        plu_path = os.path.join(cls_path, plu)
        if not os.path.isdir(plu_path): continue
        imgs = glob(os.path.join(plu_path, "*.[jp][pn]g*"))
        all_paths.extend(imgs)
        all_labels.extend([class_to_idx[cls]] * len(imgs))

all_paths = np.array(all_paths)
all_labels = np.array(all_labels)

def get_model():
    model = timm.create_model('convnext_large.fb_in22k_ft_in1k', pretrained=True, num_classes=15, drop_path_rate=0.4)
    return model.to(cfg.DEVICE)

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0
    y_true, y_pred = [], []
    for x, y in loader:
        x, y = x.to(cfg.DEVICE), y.to(cfg.DEVICE)
        with autocast(device_type=cfg.DEVICE.type):
            logits = model(x)
            loss = loss_fn(logits, y)
        total_loss += loss.item() * y.size(0)
        preds = logits.argmax(dim=1)
        correct += (preds == y).sum().item()
        total += y.size(0)
        y_true.extend(y.cpu().numpy())
        y_pred.extend(preds.cpu().numpy())

    return f1_score(y_true, y_pred, average='weighted')

loss_fn = FocalLoss(gamma=2.0, label_smoothing=0.1)

# 6. Функция обучения
def train_one_stage(model, model_ema, optimizer, scheduler, train_loader, val_loader,
                    epochs, stage_name, fold, start_epoch=0, initial_best_f1=0.0):
    scaler = GradScaler('cuda')
    best_f1 = initial_best_f1
    swa_model = AveragedModel(model) if stage_name == "STAGE2" else None
    swa_scheduler = SWALR(optimizer, swa_lr=1e-6) if swa_model else None
    epochs_no_improve = 0

    for epoch in range(start_epoch, epochs):
        model.train()
        pbar = tqdm(train_loader, desc=f"Fold {fold} | {stage_name} Ep {epoch+1}/{epochs}", leave=False)
        optimizer.zero_grad()

        # Обновляем LR scheduler от timm в начале эпохи (для WarmUp)
        if isinstance(scheduler, CosineLRScheduler):
            scheduler.step(epoch)

        for i, (x, y) in enumerate(pbar):
            x, y = x.to(cfg.DEVICE), y.to(cfg.DEVICE)

            if stage_name == "STAGE2" and random.random() > 0.5:
                if random.random() > 0.5:
                    x, y_a, y_b, lam = mixup_data(x, y)
                else:
                    x, y_a, y_b, lam = cutmix_data(x, y)
            else:
                y_a = y_b = y
                lam = 1.0

            with autocast(device_type=cfg.DEVICE.type):
                logits = model(x)
                loss = lam * loss_fn(logits, y_a) + (1 - lam) * loss_fn(logits, y_b)
                loss = loss / cfg.ACCUM_STEPS

            scaler.scale(loss).backward()

            if (i + 1) % cfg.ACCUM_STEPS == 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()
                if model_ema: model_ema.update(model)

            pbar.set_postfix(loss=loss.item() * cfg.ACCUM_STEPS)

        # Валидация (используем EMA-модель, если она есть)
        val_model = model_ema.module if model_ema else model
        f1_w = evaluate(val_model, val_loader)

        if f1_w > best_f1:
            best_f1 = f1_w
            save_best(val_model, f1_w, epoch, fold)
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        # Обновляем стандартный PyTorch scheduler, если это Stage 1
        if not isinstance(scheduler, CosineLRScheduler) and scheduler:
            scheduler.step()

        if swa_model and epoch >= epochs - 5:
            swa_model.update_parameters(model)
            if swa_scheduler: swa_scheduler.step()

        print(f"Fold {fold} | {stage_name} Ep {epoch+1} | Val F1_w = {f1_w:.5f} | Best = {best_f1:.5f}")

        if epochs_no_improve >= cfg.PATIENCE:
            print("Early stopping triggered")
            break

    if swa_model:
        torch.optim.swa_utils.update_bn(train_loader, swa_model)
        save_best(swa_model.module, best_f1, "SWA", fold)
        return swa_model.module

    return model

resume_info = None
if cfg.RESUME_CHECKPOINT and os.path.exists(cfg.RESUME_CHECKPOINT):
    resume_info = parse_checkpoint_name(cfg.RESUME_CHECKPOINT)
    print(f"Found Resume Info: {resume_info}")

skf = StratifiedKFold(n_splits=cfg.N_FOLDS, shuffle=True, random_state=cfg.SEED)
for fold, (train_idx, val_idx) in enumerate(skf.split(all_paths, all_labels)):

    print(f"\n{'='*40}\nSTARTING FOLD {fold}\n{'='*40}")
    train_ds = MyDataset(all_paths[train_idx], all_labels[train_idx], train_transforms)
    val_ds   = MyDataset(all_paths[val_idx], all_labels[val_idx], val_transforms)

    train_loader = DataLoader(train_ds, batch_size=cfg.BATCH_SIZE, shuffle=True, num_workers=cfg.NUM_WORKERS, pin_memory=True, drop_last=True)
    val_loader   = DataLoader(val_ds, batch_size=cfg.VAL_BATCH_SIZE, shuffle=False, num_workers=cfg.NUM_WORKERS, pin_memory=True)

    model = get_model()

    # Логика возобновления (RESUME)
    start_epoch_stage1 = 0
    start_epoch_stage2 = 0
    best_f1_stage2 = 0.0
    load_weights = False

    if resume_info and fold == resume_info['fold']:
        print(f"RESUMING Fold {fold} from Epoch {resume_info['epoch']} (F1: {resume_info['f1']})")
        # Загружаем веса в модель
        model.load_state_dict(torch.load(cfg.RESUME_CHECKPOINT, map_location=cfg.DEVICE))

        # Определяем, на каком этапе остановились
        # Stage 1 длится cfg.N_EPOCHS_STAGE1 (4 эпохи)
        if resume_info['epoch'] >= cfg.N_EPOCHS_STAGE1:
            print("-> Skipping Stage 1 (Head Only)")
            start_epoch_stage2 = resume_info['epoch'] # Продолжаем с этой эпохи в Stage 2
            best_f1_stage2 = resume_info['f1']
            load_weights = True # Веса уже загружены выше
        else:
            print("-> Resuming Stage 1")
            start_epoch_stage1 = resume_info['epoch']

    # STAGE 1: Учим только голову
    if not load_weights: # Если не загрузили веса для Stage 2, тренируем Stage 1
        print(f"--- FOLD {fold}: STAGE 1 (Head Only) ---")
        for p in model.parameters(): p.requires_grad = False
        for p in model.head.parameters(): p.requires_grad = True

        opt1 = torch.optim.AdamW(model.head.parameters(), lr=2e-3, weight_decay=0.01)
        sched1 = torch.optim.lr_scheduler.CosineAnnealingLR(opt1, T_max=cfg.N_EPOCHS_STAGE1)

        train_one_stage(model, None, opt1, sched1, train_loader, val_loader,
                        cfg.N_EPOCHS_STAGE1, "STAGE1", fold, start_epoch=start_epoch_stage1)

    # Подготовка к Stage 2
    model_ema = ModelEmaV2(model, decay=0.9998)

    # STAGE 2: Файнтюнинг всей сети с Warm-Up
    # Запускаем Stage 2 всегда, но если weights loaded, то пропускаем инициализацию весов
    print(f"--- FOLD {fold}: STAGE 2 (Full Model + WarmUp + SWA) ---")
    for p in model.parameters(): p.requires_grad = True

    opt2 = torch.optim.AdamW(model.parameters(), lr=5e-5, weight_decay=0.05)

    sched2 = CosineLRScheduler(
        opt2,
        t_initial=cfg.N_EPOCHS_STAGE2,
        lr_min=1e-6,
        warmup_t=3,
        warmup_lr_init=1e-7
    )

    # Если мы загрузили веса вручную, нам не нужно тренировать с 0, передаем start_epoch
    train_one_stage(model, model_ema, opt2, sched2, train_loader, val_loader,
                    cfg.N_EPOCHS_STAGE2, "STAGE2", fold,
                    start_epoch=start_epoch_stage2, initial_best_f1=best_f1_stage2)

    # Очищаем память перед следующим фолдом
    del model, model_ema, opt1, opt2, sched1, sched2, train_loader, val_loader
    torch.cuda.empty_cache()
    gc.collect()

# 8. Инференс: Ансамбль 5 фолдов + TTA
class TestDatasetTTA(Dataset):
    def __init__(self, paths, transforms):
        self.paths = paths
        self.transforms = transforms

    def __len__(self): return len(self.paths)
    def __getitem__(self, i):
        img = cv2.imdecode(np.fromfile(self.paths[i], dtype=np.uint8), cv2.IMREAD_COLOR)
        if img is None: img = np.zeros((cfg.IMG_SIZE, cfg.IMG_SIZE, 3), dtype=np.uint8)
        else: img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Генерируем пачку TTA-изображений для одной картинки
        return torch.stack([tf(image=img)['image'] for tf in self.transforms])


print("\nLaunching Final Inference...")
test_dir = os.path.join(data_path, "test_images", "test_images")
sub = pd.read_csv(os.path.join(data_path, "sample_submission.csv"))
test_paths = [os.path.join(test_dir, img_id) for img_id in sub["image_id"]]

test_ds = TestDatasetTTA(test_paths, tta_transforms)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False, num_workers=cfg.NUM_WORKERS, pin_memory=True)

final_probs = np.zeros((len(test_paths), 15))
best_models = sorted(glob(os.path.join(cfg.BEST_MODELS_DIR, "best_fold*.pth")))

# Загружаем пустую модель 1 раз
model = get_model()

for m_path in best_models:
    print(f"Predicting with: {os.path.basename(m_path)}")
    model.load_state_dict(torch.load(m_path, map_location=cfg.DEVICE))
    model.eval()

    model_probs = []
    with torch.no_grad():
        for x in tqdm(test_loader, desc="TTA Inference"):
            # x: [1, num_tta, C, H, W] -> [num_tta, C, H, W]
            x = x.squeeze(0).to(cfg.DEVICE)

            # Защита от OOM при большом количестве TTA
            img_probs = []
            for i in range(0, x.size(0), cfg.VAL_BATCH_SIZE):
                x_chunk = x[i : i + cfg.VAL_BATCH_SIZE]
                with autocast(device_type=cfg.DEVICE.type):
                    probs = F.softmax(model(x_chunk), dim=1)
                img_probs.append(probs.cpu().numpy())

            # Усредняем вероятности всех TTA для одной картинки
            img_probs = np.concatenate(img_probs, axis=0).mean(axis=0)
            model_probs.append(img_probs)

    # Добавляем предсказания модели в общий ансамбль
    final_probs += np.array(model_probs) / len(best_models)

sub["label"] = final_probs.argmax(axis=1)
sub.to_csv(cfg.SUBMISSION_PATH, index=False)
print(f"Ensemble Submission saved to {cfg.SUBMISSION_PATH}")
